'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function ParentPage() {
  const router = useRouter();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState('report');
  const [memos, setMemos] = useState<any[]>([]);
  const [newMemo, setNewMemo] = useState('');
  const [showCounselForm, setShowCounselForm] = useState(false);
  const [counselType, setCounselType] = useState('PHONE');
  const [counselDesc, setCounselDesc] = useState('');

  useEffect(() => {
    fetch('/api/parent/data').then(r => { if (!r.ok) { router.push('/auth/login'); return null; } return r.json(); }).then(d => { if (d) { setData(d); if (d.students?.[0]) fetchMemos(d.students[0].id); } }).catch(() => router.push('/auth/login')).finally(() => setLoading(false));
  }, [router]);

  const fetchMemos = (sid: string) => { fetch('/api/parent/memo?studentId=' + sid).then(r => r.json()).then(setMemos).catch(() => {}); };
  const sendMemo = async () => { if (!newMemo.trim() || !data?.students?.[0]) return; await fetch('/api/parent/memo', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ studentId: data.students[0].id, content: newMemo }) }); setNewMemo(''); fetchMemos(data.students[0].id); };
  const submitCounsel = async () => { if (!data?.students?.[0]) return; await fetch('/api/counseling', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ studentId: data.students[0].id, title: counselType === 'PHONE' ? '\uc804\ud654\uc0c1\ub2f4 \uc694\uccad' : '\ubc29\ubb38\uc0c1\ub2f4 \uc694\uccad', description: counselDesc, counselingType: counselType }) }); alert('\uc0c1\ub2f4 \uc694\uccad\uc774 \uc811\uc218\ub418\uc5c8\uc2b5\ub2c8\ub2e4.'); setShowCounselForm(false); setCounselDesc(''); };
  const handleLogout = async () => { await fetch('/api/auth/logout', { method: 'POST' }); router.push('/auth/login'); };
  const getYtId = (url: string) => { const m = url.match(/(?:youtu\.be\/|v=)([^&]+)/); return m ? m[1] : null; };

  if (loading) return <div className="min-h-screen flex items-center justify-center bg-gray-50"><p>\ub85c\ub529 \uc911...</p></div>;
  if (!data) return null;
  const s = data.students?.[0];

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white border-b sticky top-0 z-40 px-4 py-3 flex justify-between items-center"><h1 className="text-xl font-bold">\uc218\ud559\ud0d0\uad6c</h1><div className="flex items-center gap-3"><span className="text-sm text-gray-600">{data.user.name}</span><button onClick={handleLogout} className="text-xs text-red-500 border border-red-300 px-2 py-1 rounded">\ub85c\uadf8\uc544\uc6c3</button></div></div>
      {s && <div className="bg-blue-600 text-white p-4"><p className="font-bold text-lg">{s.name}</p><p className="text-sm opacity-80">{s.school||''} {s.grade?s.grade+'\ud559\ub144':''}</p></div>}
      <div className="flex overflow-x-auto border-b bg-white">{[{id:'report',l:'\ub9ac\ud3ec\ud2b8'},{id:'grades',l:'\uc131\uc801/\ucd9c\uacb0'},{id:'notice',l:'\uacf5\uc9c0'},{id:'video',l:'\uc218\uc5c5\uc601\uc0c1'},{id:'counsel',l:'\uc0c1\ub2f4\uc694\uccad'},{id:'memo',l:'\uba54\ubaa8'}].map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={'flex-shrink-0 px-4 py-3 text-sm font-medium border-b-2 '+(tab===t.id?'text-blue-600 border-blue-600':'text-gray-500 border-transparent')}>{t.l}</button>)}</div>
      <div className="p-4 max-w-2xl mx-auto">
        {tab==='report'&&<div className="space-y-4"><h2 className="text-lg font-bold">\ub370\uc77c\ub9ac \ub9ac\ud3ec\ud2b8</h2>{data.dailyReports.length===0?<p className="text-gray-500 text-sm">\ucd5c\uadfc \ub9ac\ud3ec\ud2b8\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.</p>:data.dailyReports.map((r:any)=><div key={r.id} className="bg-white border rounded-lg p-4 shadow-sm"><div className="flex justify-between mb-2"><span className="text-sm font-medium text-blue-600">{r.classroom?.subject?.name}</span><span className="text-xs text-gray-400">{r.date}</span></div>{r.content&&<div className="mb-2"><p className="text-xs text-gray-500">\uc218\uc5c5\uc9c4\ub3c4</p><p className="text-sm">{r.content}</p></div>}{r.homework&&<div className="mb-2"><p className="text-xs text-gray-500">\uc219\uc81c</p><p className="text-sm font-medium">{r.homework}</p></div>}{r.specialNote&&<div><p className="text-xs text-gray-500">\uacf5\uc9c0</p><p className="text-sm">{r.specialNote}</p></div>}</div>)}</div>}
        {tab==='grades'&&<div className="space-y-6"><div><h2 className="text-lg font-bold mb-3">\uc131\uc801</h2>{data.grades.length===0?<p className="text-gray-500 text-sm">\uc131\uc801 \uae30\ub85d\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.</p>:<div className="space-y-2">{data.grades.map((g:any)=><div key={g.id} className="bg-white border rounded-lg p-3 flex justify-between"><div><p className="text-sm font-medium">{g.testName}</p><p className="text-xs text-gray-400">{g.testDate}</p></div><p className="text-lg font-bold text-blue-600">{g.score}<span className="text-sm text-gray-400">/{g.maxScore}</span></p></div>)}</div>}</div><div><h2 className="text-lg font-bold mb-3">\ucd9c\uacb0</h2>{data.attendance.length===0?<p className="text-gray-500 text-sm">\ucd9c\uacb0 \uae30\ub85d\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.</p>:<div className="space-y-2">{data.attendance.map((a:any)=><div key={a.id} className="bg-white border rounded-lg p-3 flex justify-between"><div><p className="text-sm">{a.date}</p><p className="text-xs text-gray-400">{a.classroom?.subject?.name}</p></div><span className={'px-2 py-1 rounded text-xs font-medium '+(a.status==='PRESENT'?'bg-green-100 text-green-800':a.status==='ABSENT'?'bg-red-100 text-red-800':'bg-yellow-100 text-yellow-800')}>{a.status==='PRESENT'?'\ucd9c\uc11d':a.status==='ABSENT'?'\uacb0\uc11d':'\uc9c0\uac01'}</span></div>)}</div>}</div></div>}
        {tab==='notice'&&<div className="space-y-4"><h2 className="text-lg font-bold">\uacf5\uc9c0\uc0ac\ud56d</h2>{data.announcements.length===0?<p className="text-gray-500 text-sm">\uacf5\uc9c0\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.</p>:data.announcements.map((a:any)=><div key={a.id} className="bg-white border rounded-lg p-4"><p className="font-medium">{a.title}</p><p className="text-sm text-gray-600 mt-1 whitespace-pre-wrap">{a.content}</p><p className="text-xs text-gray-400 mt-2">{new Date(a.publishDate).toLocaleDateString('ko-KR')}</p></div>)}</div>}
        {tab==='video'&&<div className="space-y-4"><h2 className="text-lg font-bold">\uc218\uc5c5 \uc601\uc0c1</h2>{data.videos.length===0?<p className="text-gray-500 text-sm">\uc601\uc0c1\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.</p>:data.videos.map((v:any)=>{const yi=getYtId(v.videoUrl);return <div key={v.id} className="bg-white border rounded-lg overflow-hidden">{yi?<iframe className="w-full aspect-video" src={'https://www.youtube.com/embed/'+yi} allowFullScreen/>:<a href={v.videoUrl} target="_blank" className="block p-4 text-blue-600">{v.videoUrl}</a>}<div className="p-3"><p className="font-medium text-sm">{v.title}</p><p className="text-xs text-gray-400">{v.date}</p></div></div>})}</div>}
        {tab==='counsel'&&<div className="space-y-4"><h2 className="text-lg font-bold">\uc0c1\ub2f4 \uc694\uccad</h2>{!showCounselForm?<div className="space-y-3"><button onClick={()=>{setCounselType('PHONE');setShowCounselForm(true)}} className="w-full p-4 bg-white border rounded-lg text-left hover:bg-blue-50"><p className="font-medium">\ud83d\udcde \uc804\ud654 \uc0c1\ub2f4 \uc694\uccad</p><p className="text-sm text-gray-500">\uc120\uc0dd\ub2d8\uc774 \uc804\ud654\ub97c \ub4dc\ub9bd\ub2c8\ub2e4</p></button><button onClick={()=>{setCounselType('VISIT');setShowCounselForm(true)}} className="w-full p-4 bg-white border rounded-lg text-left hover:bg-green-50"><p className="font-medium">\ud83c\udfeb \ubc29\ubb38 \uc0c1\ub2f4 \uc694\uccad</p><p className="text-sm text-gray-500">\ud559\uc6d0\uc5d0 \ubc29\ubb38\ud558\uc5ec \uc0c1\ub2f4</p></button></div>:<div className="bg-white border rounded-lg p-4 space-y-3"><p className="font-medium">{counselType==='PHONE'?'\uc804\ud654':'\ubc29\ubb38'} \uc0c1\ub2f4 \uc694\uccad</p><textarea value={counselDesc} onChange={e=>setCounselDesc(e.target.value)} placeholder="\uc0c1\ub2f4 \ub0b4\uc6a9\uc744 \uc785\ub825\ud574\uc8fc\uc138\uc694" rows={3} className="w-full border rounded-lg px-3 py-2 text-sm"/><div className="flex gap-2"><button onClick={()=>setShowCounselForm(false)} className="flex-1 py-2 border rounded-lg text-sm">\ucde8\uc18c</button><button onClick={submitCounsel} className="flex-1 py-2 bg-blue-600 text-white rounded-lg text-sm">\uc694\uccad\ud558\uae30</button></div></div>}</div>}
        {tab==='memo'&&<div className="space-y-4"><h2 className="text-lg font-bold">\uba54\ubaa8</h2><div className="bg-white border rounded-lg p-4 space-y-3 max-h-96 overflow-y-auto">{memos.length===0?<p className="text-gray-500 text-sm text-center">\uba54\ubaa8\uac00 \uc5c6\uc2b5\ub2c8\ub2e4</p>:memos.map((m:any)=><div key={m.id} className={'p-3 rounded-lg max-w-[80%] '+(m.isFromParent?'bg-blue-100 ml-auto':'bg-gray-100 mr-auto')}><p className="text-sm">{m.content}</p><p className="text-xs text-gray-400 mt-1">{m.author?.name}</p></div>)}</div><div className="flex gap-2"><input type="text" value={newMemo} onChange={e=>setNewMemo(e.target.value)} placeholder="\uba54\ubaa8\ub97c \uc785\ub825\ud558\uc138\uc694..." className="flex-1 border rounded-lg px-3 py-2 text-sm" onKeyDown={e=>e.key==='Enter'&&sendMemo()}/><button onClick={sendMemo} disabled={!newMemo.trim()} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm disabled:bg-gray-400">\uc804\uc1a1</button></div></div>}
      </div>
    </div>
  );
}
